apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-analyzer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: traffic-analyzer
  template:
    metadata:
      labels:
        app: traffic-analyzer
    spec:
      containers:
        - name: app
          image: yogramming/traffic-analyzer:13
          ports:
            - containerPort: 5000
